import { useState, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import { useTemplates } from '@/hooks/use-templates';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { toast } from 'sonner';
import { Sparkles, Wand2, Save, BookOpen, Bold, Italic, Link2, List, ChevronDown } from 'lucide-react';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { MERGE_FIELDS } from '@/lib/merge-fields';
import TemplateLibrary from './TemplateLibrary';
import type { CampaignTemplate } from '@/types/crm';

interface TemplateEditorProps {
  subject: string;
  body: string;
  onSubjectChange: (s: string) => void;
  onBodyChange: (b: string) => void;
}

export default function TemplateEditor({ subject, body, onSubjectChange, onBodyChange }: TemplateEditorProps) {
  const { createTemplate } = useTemplates();
  const bodyRef = useRef<HTMLTextAreaElement>(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [showAiPanel, setShowAiPanel] = useState(false);
  const [showLibrary, setShowLibrary] = useState(false);
  const [showSaveDialog, setShowSaveDialog] = useState(false);
  const [templateName, setTemplateName] = useState('');

  const insertField = (tag: string) => {
    const textarea = bodyRef.current
    if (!textarea) { onBodyChange(body + tag); return }
    const start = textarea.selectionStart
    const end = textarea.selectionEnd
    const newValue = body.slice(0, start) + tag + body.slice(end)
    onBodyChange(newValue)
    requestAnimationFrame(() => {
      textarea.focus()
      textarea.setSelectionRange(start + tag.length, start + tag.length)
    })
  }

  const handleGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-template', {
        body: { mode: 'generate', prompt: aiPrompt.trim() },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      onSubjectChange(data.subject);
      onBodyChange(data.body);
      setShowAiPanel(false);
      setAiPrompt('');
      toast.success('Template generated by AI');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'AI generation failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleCleanup = async () => {
    if (!subject.trim() && !body.trim()) { toast.error('Write something first for AI to improve'); return; }
    setAiLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-template', {
        body: { mode: 'cleanup', existingSubject: subject, existingBody: body },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      onSubjectChange(data.subject);
      onBodyChange(data.body);
      toast.success('Template improved by AI');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'AI cleanup failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleSaveTemplate = async () => {
    if (!templateName.trim() || !subject.trim()) return;
    try {
      await createTemplate({ name: templateName.trim(), subject, body });
      toast.success('Template saved');
      setShowSaveDialog(false);
      setTemplateName('');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to save template');
    }
  };

  const handleLoadTemplate = (template: CampaignTemplate) => {
    onSubjectChange(template.subject);
    onBodyChange(template.body);
    setShowLibrary(false);
    toast.success(`Loaded template: ${template.name}`);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 flex-wrap">
        <Button variant={showAiPanel ? 'default' : 'outline'} size="sm" className="gap-1.5" onClick={() => setShowAiPanel(!showAiPanel)}>
          <Sparkles className="h-3.5 w-3.5" /> AI Generate
        </Button>
        <Button variant="outline" size="sm" className="gap-1.5" onClick={handleCleanup} disabled={aiLoading}>
          <Wand2 className="h-3.5 w-3.5" /> {aiLoading ? 'Improving...' : 'AI Improve'}
        </Button>
        <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setShowLibrary(!showLibrary)}>
          <BookOpen className="h-3.5 w-3.5" /> Templates
        </Button>
        {(subject.trim() || body.trim()) && (
          <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setShowSaveDialog(true)}>
            <Save className="h-3.5 w-3.5" /> Save Template
          </Button>
        )}
      </div>

      {showAiPanel && (
        <Card className="border bg-muted/30">
          <CardContent className="p-4 space-y-3">
            <p className="text-xs text-muted-foreground">Describe the email you want to send:</p>
            <Textarea placeholder="e.g., Cold outreach to SaaS CTOs about our API integration platform. Professional but casual tone." value={aiPrompt} onChange={e => setAiPrompt(e.target.value)} className="min-h-[80px]" />
            <Button size="sm" onClick={handleGenerate} disabled={aiLoading || !aiPrompt.trim()} className="gap-1.5">
              <Sparkles className="h-3.5 w-3.5" /> {aiLoading ? 'Generating...' : 'Generate Template'}
            </Button>
          </CardContent>
        </Card>
      )}

      {showLibrary && (
        <Card className="border">
          <CardContent className="p-4">
            <TemplateLibrary onSelect={handleLoadTemplate} />
          </CardContent>
        </Card>
      )}

      <div className="space-y-2">
        <Label>Subject</Label>
        <Input placeholder="Email subject line..." value={subject} onChange={e => onSubjectChange(e.target.value)} />
      </div>

      <div className="space-y-2">
        <Label>Body</Label>
        <div className="flex items-center gap-0.5 px-2 py-1.5 border rounded-t-md bg-muted/30 border-b-0">
          <Button type="button" variant="ghost" size="icon" className="h-7 w-7" title="Bold" onMouseDown={e => e.preventDefault()}><Bold className="h-3.5 w-3.5" /></Button>
          <Button type="button" variant="ghost" size="icon" className="h-7 w-7" title="Italic" onMouseDown={e => e.preventDefault()}><Italic className="h-3.5 w-3.5" /></Button>
          <Button type="button" variant="ghost" size="icon" className="h-7 w-7" title="Link" onMouseDown={e => e.preventDefault()}><Link2 className="h-3.5 w-3.5" /></Button>
          <Button type="button" variant="ghost" size="icon" className="h-7 w-7" title="List" onMouseDown={e => e.preventDefault()}><List className="h-3.5 w-3.5" /></Button>
          <div className="w-px h-4 bg-border mx-1" />
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button type="button" variant="ghost" size="sm" className="h-7 text-xs gap-1" onMouseDown={e => e.preventDefault()}>
                Add Field <ChevronDown className="h-3 w-3" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              {MERGE_FIELDS.map(field => (
                <DropdownMenuItem key={field.tag} onSelect={() => insertField(field.tag)}>
                  {field.label} <span className="ml-auto text-xs text-muted-foreground pl-4">{field.tag}</span>
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <Textarea ref={bodyRef} placeholder="Write your email body... Use {{firstName}} and {{company}} for personalization." value={body} onChange={e => onBodyChange(e.target.value)} className="min-h-[200px] rounded-t-none" />
      </div>

      <Dialog open={showSaveDialog} onOpenChange={setShowSaveDialog}>
        <DialogContent>
          <DialogHeader><DialogTitle>Save Template</DialogTitle></DialogHeader>
          <div className="space-y-2">
            <Label>Template Name</Label>
            <Input placeholder="e.g., Cold Outreach - SaaS" value={templateName} onChange={e => setTemplateName(e.target.value)} />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowSaveDialog(false)}>Cancel</Button>
            <Button onClick={handleSaveTemplate} disabled={!templateName.trim()}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
